import FormatMoney from './Format/Forrmat-money.js'
import FormatDate from './Format/Format-date.js'
import Regex_Email from './Regex/Regex-Email.js'
import Regex_Phone from './Regex/Regex-Phone.js'
import Regex_UserName from './Regex/Regex-UserName.js'
import Regex_URLs from './Regex/Regex-URLs.js'
import ToCapitalize from './CapitalizeLetter/ToCapitalize.js'
